---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-raring32
    driver:
      box: ubuntu-raring32
      box_url: http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-i386-vagrant-disk1.box

suites:
  - name: default
    run_list:
      - recipe[apps::pictesfootball]
    attributes:
