---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-precise32
    driver:
      box: ubuntu-precise32
      box_url: http://files.vagrantup.com/precise32.box

suites:
  - name: default
    run_list:
      - recipe[apps::pictesfootball]
    attributes:
